plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleLength:
  Exclude:
    - spec/**/*_conformance_spec.rb
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExpectActual:
  Exclude:
    - spec/**/*_conformance_spec.rb
